-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF JOIN ICECREAM_INFO USING(FLAVOR) # FIRST_HALF랑 ICECREAM_INFO를 FLAVOR열 기준으로 합친 테이블에서 FLAVOR를 가져옴
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
