-- 코드를 입력하세요
# SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD AS A, USED_GOODS_REPLY AS B
# WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10 AND A.BOARD_ID = B.BOARD_ID
# # WHERE B.CREATED_DATE LIKE '2022-10%' AND A.BOARD_ID = B.BOARD_ID AND B.CONTENTS IS NOT NULL
# ORDER BY B.CREATED_DATE, TITLE
SELECT TITLE, a.BOARD_ID, REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
From USED_GOODS_BOARD as a, USED_GOODS_REPLY as b
where  a.BOARD_ID = b.BOARD_ID
and a.CREATED_DATE LIKE "2022-10%"
order by b.CREATED_DATE,TITLE